use super::*;

#[test]
fn generated_reference_contains_every_catalog_rule() {
    let document = markdown();

    assert!(
        document.starts_with("<!-- Generated by `make generate-rules`; do not edit manually. -->")
    );
    assert!(document.contains("### `js` catalog (9 rules)"));
    assert!(document.contains("### `obsidian` catalog (49 rules)"));
    assert!(document.contains("#### `browser:network.request`"));
    assert!(document.contains("#### `obsidian:network.request`"));
    assert!(document.contains("Emit `fetch` when a call to the global `fetch`."));
    assert!(!document.lines().any(|line| line.starts_with('|')));
    assert_eq!(
        document
            .lines()
            .filter(|line| line.starts_with("#### `"))
            .count(),
        85
    );
}

#[test]
fn checked_in_reference_matches_the_generator() {
    assert_eq!(markdown(), include_str!("../../../RULES.md"));
}
