//! Generation and verification of the repository-wide rule reference.

use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result, bail};
use glass_lint_core::RuleMetadata;

#[derive(Debug)]
struct CatalogDocumentation {
    name: &'static str,
    rules: Vec<RuleMetadata>,
}

/// Build the complete metadata set from every provider catalog in catalog
/// order. Catalog order is part of the generated document's stable layout.
fn catalogs() -> [CatalogDocumentation; 5] {
    glass_lint_obsidian::ObsidianCatalogBundle::new()
        .metadata_by_catalog()
        .into_iter()
        .map(|(name, rules)| CatalogDocumentation { name, rules })
        .collect::<Vec<_>>()
        .try_into()
        .expect("Obsidian catalog bundle has five provider catalogs")
}

/// Render the complete rule reference as deterministic Markdown.
pub fn markdown() -> String {
    let mut document = String::new();
    document.push_str("<!-- Generated by `make generate-rules`; do not edit manually. -->\n\n");
    document.push_str("# Glass Lint rules\n\n");
    document.push_str(
        "This document is generated from the provider rule catalogs. Each rule lists the exact matcher queries that produce findings.\n\n",
    );

    for catalog in catalogs() {
        let _ = writeln!(
            document,
            "### `{}` catalog ({} rules)\n",
            catalog.name,
            catalog.rules.len()
        );
        for rule in catalog.rules {
            let _ = writeln!(
                document,
                "#### `{}`\n\nDefault severity: `{}`\n\nQueries:\n",
                rule.id(),
                rule.default_severity()
            );
            for explanation in rule.query_explanations() {
                let _ = writeln!(document, "- {explanation}");
            }
            document.push('\n');
        }
    }
    document
}

/// Generate the document at `output`, or verify that it is current.
pub fn write_or_check(output: &Path, check: bool) -> Result<()> {
    let expected = markdown();
    if check {
        let actual = fs::read_to_string(output)
            .with_context(|| format!("read generated rule document {}", output.display()))?;
        if actual != expected {
            bail!(
                "{} is out of date; run `make generate-rules`",
                output.display()
            );
        }
        return Ok(());
    }

    fs::write(output, expected)
        .with_context(|| format!("write generated rule document {}", output.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests;
