//! Generation and verification of the repository-wide rule reference.

use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result, bail};
use glass_lint_core::RuleMetadata;

struct CatalogDocumentation {
    name: &'static str,
    rules: Vec<RuleMetadata>,
}

/// Build the complete metadata set from every provider catalog in catalog
/// order. Catalog order is part of the generated document's stable layout.
fn catalogs() -> [CatalogDocumentation; 5] {
    [
        CatalogDocumentation {
            name: "js",
            rules: glass_lint_js::js_catalog().metadata(),
        },
        CatalogDocumentation {
            name: "browser",
            rules: glass_lint_js::browser_catalog().metadata(),
        },
        CatalogDocumentation {
            name: "node",
            rules: glass_lint_js::node_catalog().metadata(),
        },
        CatalogDocumentation {
            name: "electron",
            rules: glass_lint_js::electron_catalog().metadata(),
        },
        CatalogDocumentation {
            name: "obsidian",
            rules: glass_lint_obsidian::obsidian_catalog().metadata(),
        },
    ]
}

/// Render the complete rule reference as deterministic Markdown.
pub fn markdown() -> String {
    let mut document = String::new();
    document.push_str("<!-- Generated by `make generate-rules`; do not edit manually. -->\n\n");
    document.push_str("# Glass Lint rules\n\n");
    document.push_str(
        "This document is generated from the provider rule catalogs. Each rule lists the exact matcher queries that produce findings.\n\n",
    );

    for catalog in catalogs() {
        let _ = writeln!(
            document,
            "### `{}` catalog ({} rules)\n",
            catalog.name,
            catalog.rules.len()
        );
        for rule in catalog.rules {
            let _ = writeln!(
                document,
                "#### `{}`\n\nDefault severity: `{}`\n\nQueries:\n",
                rule.id, rule.default_severity
            );
            for explanation in rule.query_explanations {
                let _ = writeln!(document, "- {explanation}");
            }
            document.push('\n');
        }
    }
    document
}

/// Generate the document at `output`, or verify that it is current.
pub fn write_or_check(output: &Path, check: bool) -> Result<()> {
    let expected = markdown();
    if check {
        let actual = fs::read_to_string(output)
            .with_context(|| format!("read generated rule document {}", output.display()))?;
        if actual != expected {
            bail!(
                "{} is out of date; run `make generate-rules`",
                output.display()
            );
        }
        return Ok(());
    }

    fs::write(output, expected)
        .with_context(|| format!("write generated rule document {}", output.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_reference_contains_every_catalog_rule() {
        let document = markdown();

        assert!(
            document
                .starts_with("<!-- Generated by `make generate-rules`; do not edit manually. -->")
        );
        assert!(document.contains("### `js` catalog (7 rules)"));
        assert!(document.contains("### `obsidian` catalog (49 rules)"));
        assert!(document.contains("#### `browser:network.request`"));
        assert!(document.contains("#### `obsidian:network.request`"));
        assert!(document.contains("Emit `fetch` when a call to the global `fetch`."));
        assert!(!document.lines().any(|line| line.starts_with('|')));
        assert_eq!(
            document
                .lines()
                .filter(|line| line.starts_with("#### `"))
                .count(),
            82
        );
    }

    #[test]
    fn checked_in_reference_matches_the_generator() {
        assert_eq!(markdown(), include_str!("../../RULES.md"));
    }
}
