//! Node HTTP-module rule definition.

use glass_lint_core::rules::{Confidence, Matcher, Rule, Severity};

/// Detects static ESM or unshadowed CommonJS loads of the configured Node
/// network modules and exact client packages. It reports the module load
/// itself, not later API use, and relies on module provenance so similar names
/// and shadowed `require` bindings are excluded.
pub fn rule() -> Rule {
    Rule::builder("node.network")
        .description("Uses Node HTTP modules")
        .category("node/network")
        .severity(Severity::Info)
        .confidence(Confidence::High)
        .matcher(Matcher::import("http"))
        .matcher(Matcher::import("https"))
        .matcher(Matcher::import("node:http"))
        .matcher(Matcher::import("node:https"))
        .matcher(Matcher::import("http2"))
        .matcher(Matcher::import("node:http2"))
        .matcher(Matcher::import("net"))
        .matcher(Matcher::import("node:net"))
        .matcher(Matcher::import("tls"))
        .matcher(Matcher::import("node:tls"))
        .matcher(Matcher::import("dgram"))
        .matcher(Matcher::import("node:dgram"))
        .matcher(Matcher::import("dns"))
        .matcher(Matcher::import("node:dns"))
        .matcher(Matcher::import("dns/promises"))
        .matcher(Matcher::import("node:dns/promises"))
        .matcher(Matcher::package_import("undici"))
        .matcher(Matcher::package_import("axios"))
        .matcher(Matcher::package_import("node-fetch"))
        .matcher(Matcher::package_import("got"))
        .matcher(Matcher::package_import("superagent"))
        .matcher(Matcher::package_import("ws"))
        .matcher(Matcher::package_import("cross-fetch"))
        .matcher(Matcher::package_import("ky"))
        .matcher(Matcher::package_import("graphql-request"))
        .matcher(Matcher::package_import("request"))
        .matcher(Matcher::package_import("needle"))
        .matcher(Matcher::package_import("@grpc/grpc-js"))
        .matcher(Matcher::package_import("@apollo/client"))
        .matcher(Matcher::package_import("graphql"))
        .matcher(Matcher::package_import("@elastic/elasticsearch"))
        .matcher(Matcher::package_import("fetch-retry"))
        .matcher(Matcher::package_import("fetch-blob"))
        .matcher(Matcher::package_import("form-data"))
        .matcher(Matcher::package_import("http-proxy"))
        .matcher(Matcher::package_import("http-proxy-agent"))
        .matcher(Matcher::package_import("https-proxy-agent"))
        .matcher(Matcher::package_import("socks-proxy-agent"))
        .matcher(Matcher::package_import("@whatwg-node/fetch"))
        .build()
        .unwrap()
}
