[package]
name = "glass-lint-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glass-lint-datastructures = { path = "../glass-lint-datastructures" }
hashbrown.workspace = true
petgraph.workspace = true
rayon.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tracing.workspace = true
swc_common.workspace = true
swc_ecma_ast.workspace = true
swc_ecma_parser.workspace = true
swc_ecma_transforms_base.workspace = true
swc_ecma_transforms_typescript.workspace = true
swc_ecma_visit.workspace = true
smallvec.workspace = true
indexmap.workspace = true
smol_str.workspace = true

[features]
default = []
serde = [
    "dep:serde",
    "dep:serde_json",
    "smol_str/serde",
    "glass-lint-datastructures/serde",
]
telemetry = []

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
